# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-16 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedfile',
            name='user',
        ),
        migrations.DeleteModel(
            name='StagedFile',
        ),
    ]
