# Generated by Django 2.2.18 on 2021-04-07 23:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('portal', '0001_initial'), ('portal', '0002_remove_stagedfile_20170815_1726')]

    initial = True

    dependencies = []

    operations = []
