- name: Restart postgresql service
  become: true
  become_user: root
  systemd:
    name: "postgresql-12"
    state: restarted
- name: restart http server
  become: true
  systemd:
    name: httpd
    state: restarted
