- name: install and start munge
  become: true
  block:
    - name: install munge
      dnf:
        name:
          - munge
          - munge-libs
        state: present
    - name: deploy munge testing key
      copy:
        src: munge-test.key
        dest: /etc/munge/munge.key
        mode: "600"
        owner: munge
        group: munge
    - name: start munge service
      systemd:
        name: munge
        state: started
        enabled: true
