version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - ">=5.0.0"  # Waiting for https://github.com/tholo/pytest-flake8/issues/87
  - dependency-name: Django
    versions:
    - ">=4.1.0"  # Waiting for https://github.com/encode/django-rest-framework/issues/8587
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
