language: python
python:
    - "2.7"
sudo: required
services:
  - postgresql
  - docker
before_install:
    - sudo apt-get install -y -q nodejs dh-autoreconf build-essential libarchive-dev
install:
    - pip install -r requirements-dev.txt
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - nodejs --version
    - npm --version
    - npm install
    - git clone https://github.com/singularityware/singularity.git
    - cd singularity
    - git checkout -q tags/2.5.2
    - ./autogen.sh
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - cd ..
before_script:
    - sed -f travis_settings_modification.sed kive/kive/settings_default.py > kive/kive/settings.py
script:
  - set -e
  - npm run test:travis
  - cd kive
  - ./manage.py test --setting kive.settings_mocked
  - coverage run manage.py test --setting kive.settings_test_pg
  - set +e
after_success:
    - pip install codecov
    - codecov