env:
  global:
    - USER=root
language: python
python:
    - "2.7"
sudo: required
services:
  - postgresql
  - docker
# before_install:
#    - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
install: "pip install -r requirements-dev.txt"
before_script:
    - sed -f travis_settings_modification.sed kive/kive/settings_default.py > kive/kive/settings.py
    - sudo groupadd kiveprocessing
    - sudo useradd kivefleet -G kiveprocessing
    - sudo usermod -a -G kiveprocessing $USER
script:
  - cd kive
  - sudo -u kivefleet -g kiveprocessing -E printenv
  - sudo -u kivefleet -g kiveprocessing -E ./manage.py test --setting kive.settings_mocked
  - sudo -u kivefleet -g kiveprocessing -E coverage run manage.py test --setting kive.settings_test_pg
after_success:
    - pip install codecov
    - codecov