language: python
python:
    - "2.7"
    - "3.4"
sudo: required
services:
  - postgresql
  - docker
env:
  global:
    - KIVE_DB_USER=postgres
before_install:
    - sudo apt-get install -y -q nodejs dh-autoreconf build-essential libarchive-dev squashfs-tools
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -r requirements-dev.txt ;
    - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install -r requirements-dev.py34.txt ;
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - nodejs --version
    - npm --version
    - npm install
    - git clone https://github.com/singularityware/singularity.git
    - cd singularity
    - git checkout -q tags/2.5.2
    - ./autogen.sh
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - cd ..
before_script:
    - cp kive/kive/settings_default.py kive/kive/settings.py
script:
  - set -e
  - npm run test:travis
  - cd kive
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then ./manage.py test --setting kive.settings_mocked ;
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coverage run manage.py test --setting kive.settings_test_pg ;
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then ./manage.py test --setting kive.settings_mocked librarian fleet transformation stopwatch method.tests kive.tests_file_access_utils kive.tests datachecking archive portal rest_framework ;
  - cd ../api
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coverage run --source=kiveapi -m pytest ;
  - set +e
after_success:
    - pip install codecov
    - codecov
    - cd ../kive
    - codecov
