language: python
python:
    - "2.7"
dist: trusty
sudo: required
services: postgresql
before_install:
    - sudo apt-get install -y -q openmpi-bin libopenmpi-dev munge slurm-llnl slurm-llnl-basic-plugins
    - sudo chmod g-w /var/log
    - sudo /usr/sbin/create-munge-key
    - sudo service munge start
    - sudo cp travis_slurm.conf /etc/slurm-llnl/slurm.conf
    - sudo service slurm-llnl start
    - echo "Testing Slurm installation by calling squeue...."
    - squeue
install: "pip install -r requirements-dev.txt"
before_script:
    - sed "s/\[YOUR DB NAME HERE\]/kive/;s/\[YOUR DB USER NAME HERE\]/postgres/;s/\[YOUR DB USER PASSWORD HERE\]//;s#MEDIA_ROOT = ''#MEDIA_ROOT = '/tmp'#" kive/kive/settings_default.py > kive/kive/settings.py
script: "cd kive && ./manage.py test --setting kive.settings_test_pg_loud fleet.test_slurmscheduler && ./manage.py test --setting kive.settings_mocked && coverage run manage.py test --setting kive.settings_test_pg"

after_success:
    - pip install codecov
    - codecov