language: python
python:
    - "2.7"
sudo: required
services: postgresql
before_install:
    - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
install: "pip install -r requirements-dev.txt"
before_script:
    - sed "s/\[YOUR DB NAME HERE\]/kive/;s/\[YOUR DB USER NAME HERE\]/postgres/;s/\[YOUR DB USER PASSWORD HERE\]//;s#MEDIA_ROOT = ''#MEDIA_ROOT = '/tmp'#" kive/kive/settings_default.py > kive/kive/settings.py
script: "cd kive && ./manage.py test --setting kive.settings_mocked && ./manage.py test --setting kive.settings_test_pg"