language: python
python:
    - "2.7"
sudo: required
before_install:
    - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
install: "pip install -r requirements-dev.txt"
script: "cd kive && cp kive/settings_default.py kive/settings.py && python -m unittest discover -p tests_mock.py"