language: python
python:
    - "2.7"
    - "3.6"
sudo: required
services:
  - postgresql
  - docker
env:
  global:
    - KIVE_DB_USER=postgres
before_install:
    - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - sudo apt-get install -y -q nodejs dh-autoreconf build-essential libarchive-dev squashfs-tools
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements-dev.txt ; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install -r requirements-dev.py34.txt ; fi
    - node --version
    - nodejs --version  # Not relevant?
    - npm --version
    - npm install
    - git clone https://github.com/singularityware/singularity.git
    - cd singularity
    - git checkout -q tags/2.5.2
    - ./autogen.sh
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - cd ..
script:
  - set -e
  - npm run test:travis
  - cd kive
  - coverage run -m pytest --ds kive.settings_test_pg
  - cd ../api
  - coverage run --source=kiveapi -m pytest
  - set +e
after_success:
    - pip install codecov
    - codecov
    - cd ../kive
    - codecov
