language: python
python:
    - "3.6"
sudo: required
services:
  - postgresql
env:
  global:
    - KIVE_DB_USER=postgres
    - KIVE_STATIC_ROOT=/tmp/kive_test_static_root
before_install:
    - sudo apt-get install -y -q dh-autoreconf build-essential libarchive-dev squashfs-tools
    - nvm install 12.13.1
    - nvm use 12.13.1
install:
    - pip install -r requirements-dev.txt
    - node --version
    - npm --version
    - npm install
    - git clone https://github.com/singularityware/singularity.git
    - cd singularity
    - git checkout -q tags/2.5.2
    - ./autogen.sh
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - cd ..
script:
  - set -e
  - npm run test:travis
  - cd kive
  - python manage.py collectstatic --no-input
  - coverage run -m pytest --flake8 --ds kive.settings_test_pg
  - cd ../api
  - coverage run --source=kiveapi -m pytest
  - set +e
after_success:
    - pip install codecov
    - codecov
    - cd ../kive
    - codecov
