# FIXME we may not need this
- name: reconfigure slurm
  become: true
  become_user: root
  command: scontrol reconfigure
  register: slurm_reconfigure_result
  changed_when: slurm_reconfigure_result.rc == 0
  failed_when:
    - slurm_reconfigure_result.rc != 0
  throttle: 1
