Vagrant.configure("2") do |config|
  # For more information on the contents of this file, see:
  #   - https://docs.vagrantup.com
  #   - https://www.vagrantup.com/docs/multi-machine/


  config.vm.box = "geerlingguy/centos7"
  config.vm.box_version = "1.2.6"

  config.vm.synced_folder "..", "/usr/local/share/Kive"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  
  config.vm.define :head do |head|
    head.vm.hostname = "head"
    head.vm.network "private_network", ip: "192.168.233.10"
    head.vm.network "forwarded_port", guest: 8000, host: 8000
    head.vm.network "forwarded_port", guest: 8080, host: 8080
    head.vm.provision :shell, path: "bootstrap-head.sh"
  end

  config.vm.define :worker, autostart: false  do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.233.11"
    worker.vm.provision :shell, path: "bootstrap-worker.sh"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8 * 1024
    vb.cpus = 4
  end
end
