# This Vagrantfile describes a test configuration with two VMs:
#
#   - `head`: hosts Kive and the Slurm control, database, and worker daemons
#   - `worker`: host a Slurm worker daemon
#
# For more information on the contents of this file, see:
#   - https://docs.vagrantup.com
#   - https://www.vagrantup.com/docs/multi-machine/

# IP addresses for the VMs are statically assigned because Vagrant
# and Virtualbox have a bad interaction that precludes DHCP configuration.
# see: https://github.com/hashicorp/vagrant/issues/3083
HEAD_IP = "192.168.233.10"
WORKER_IP = "192.168.233.11"

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"
  config.vm.box_version = "1.2.6"

  config.vm.synced_folder "..", "/usr/local/share/Kive"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define :head do |head|
    head.vm.hostname = "head"
    head.vm.network "private_network", ip: HEAD_IP
    head.vm.network "forwarded_port", guest: 8000, host: 8000
    head.vm.network "forwarded_port", guest: 8080, host: 8080
    head.vm.provision :shell, path: "bootstrap-head.sh"
  end

  config.vm.define :worker, autostart: false  do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provision :shell, path: "bootstrap-worker.sh"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8 * 1024
    vb.cpus = 4
  end

  config.vm.provision :shell,
    inline: <<-EOS
      echo "#{HEAD_IP}\thead\n#{WORKER_IP}\tworker" >> /etc/hosts
    EOS
end
