---

- become: true
  block:
    - name: install slurm from rpm files
      dnf:
        name:
          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-20.02.2-1.el8.x86_64.rpm"
          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-slurmd-20.02.2-1.el8.x86_64.rpm"

    - name: fix slurmd pidfile path in systemd unit
      replace:
        path: /usr/lib/systemd/system/slurmd.service
        regexp: var/run/slurmd.pid
        replace: /var/run/slurm/slurmd.pid

    - name: enable slurmd service
      systemd:
        daemon_reload: true  # necessary because we edited the unit file
        name: slurmd
        state: started
        enabled: true
