# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_transition_SD_to_dataset_20151117_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compounddatatype',
            name='groups_allowed',
            field=models.ManyToManyField(blank=True, help_text='What groups have access?', related_name='metadata_compounddatatype_has_access_to', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='compounddatatype',
            name='users_allowed',
            field=models.ManyToManyField(blank=True, help_text='Which users have access?', related_name='metadata_compounddatatype_has_access_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='groups_allowed',
            field=models.ManyToManyField(blank=True, help_text='What groups have access?', related_name='metadata_datatype_has_access_to', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='users_allowed',
            field=models.ManyToManyField(blank=True, help_text='Which users have access?', related_name='metadata_datatype_has_access_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
