# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_permissions_remove_null_20160203_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='restricts',
            field=models.ManyToManyField(blank=True, help_text='Captures hierarchical is-a classifications among Datatypes', related_name='restricted_by', to='metadata.Datatype'),
        ),
    ]
