# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_restricts_remove_null_20160203_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='compounddatatype',
            name='name',
            field=models.TextField(blank=True, help_text='The name of this CompoundDatatype', verbose_name='Name'),
        ),
    ]
