# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_set_cdt_names_20160215_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compounddatatype',
            options={'ordering': ['name']},
        ),
    ]
