# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_order_cdt_by_name_20160215_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='prototype',
            field=models.IntegerField(db_column='prototype_id', null=True),
        ),
    ]
