# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-07 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0102_relink_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customconstraint',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='customconstraint',
            name='verification_method',
        ),
        migrations.DeleteModel(
            name='CustomConstraint',
        ),
    ]
