# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0103_remove_custom_constraints_20170106_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicconstraint',
            name='datatype',
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='groups_allowed',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='prototype',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='restricts',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='users_allowed',
        ),
        migrations.AlterModelOptions(
            name='compounddatatype',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='compounddatatypemember',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='BasicConstraint',
        ),
        migrations.RemoveField(
            model_name='compounddatatypemember',
            name='blankable',
        ),
        migrations.RemoveField(
            model_name='compounddatatypemember',
            name='column_idx',
        ),
        migrations.RemoveField(
            model_name='compounddatatypemember',
            name='column_name',
        ),
        migrations.RemoveField(
            model_name='compounddatatypemember',
            name='datatype',
        ),
        migrations.DeleteModel(
            name='Datatype',
        ),
    ]
