# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0104_drop_datatype'),
        # ('transformation', '0104_drop_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compounddatatype',
            name='groups_allowed',
        ),
        migrations.RemoveField(
            model_name='compounddatatype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='compounddatatype',
            name='users_allowed',
        ),
        migrations.RemoveField(
            model_name='compounddatatypemember',
            name='compounddatatype',
        ),
        migrations.DeleteModel(
            name='CompoundDatatype',
        ),
        migrations.DeleteModel(
            name='CompoundDatatypeMember',
        ),
    ]
