# Generated by Django 2.2.18 on 2021-04-07 19:19

from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.core.management import call_command
from django.db import migrations, transaction


@transaction.atomic
def load_initial_groups(apps, schema_editor):
    auth_app_config = django_apps.get_app_config("auth")
    create_permissions(auth_app_config, verbosity=2)
    call_command("loaddata", "initial_groups", app_label="metadata")


def load_initial_user(apps, schema_editor):
    call_command("loaddata", "initial_user", app_label="metadata")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [('metadata', '0101_squashed'),
                ('metadata', '0102_relink_apps'),
                ('metadata', '0103_remove_custom_constraints_20170106_1628'),
                ('metadata', '0104_drop_datatype'),
                ('metadata', '0105_drop_all')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KiveUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
        ),
        migrations.RunPython(code=load_initial_groups, reverse_code=noop),
        migrations.RunPython(code=load_initial_user, reverse_code=noop),
    ]
