#! /usr/bin/env python

"""
Execute the clustalw program to perform a multiple sequence alignment.
One file is read, and one file is written.

This script will fail if the clustalw executable is not in the current PATH.
"""
from argparse import FileType, ArgumentParser
import subprocess

parser = ArgumentParser(
    description="Takes sequence datafile, outputs sequence (multiple sequence alignment) generated by the external executable clustalw.");
parser.add_argument("input_seq",
                    help="sequences to be aligned");
parser.add_argument("output_seq",
                    help="multiply aligned sequences");
args = parser.parse_args();

cmd="clustalw -infile=%s -outfile=%s"%(args.input_seq,args.output_seq)

try:
    subprocess.check_call(cmd,shell=True)
except:
    print "Call to clustalw failed."
    print "Be sure to install clustalw (on ubuntu, install package clustalw)."
    raise
print "clustalw executed successfully"


