# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 18:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_remove_pipelinefamily_published_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineoutputcable',
            name='output_name',
            field=models.CharField(help_text='Pipeline output hole name', max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Output hole name'),
        ),
    ]
