# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0016_permissions_remove_null_20160203_1033'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='PipelineStepOutputsToDeleteTemp',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('transformationoutput_id', models.IntegerField()),
                    ],
                    options={
                        'db_table': 'pipeline_pipelinestep_outputs_to_delete',
                    },
                ),
                migrations.RemoveField(
                    model_name='pipelinestep',
                    name='outputs_to_delete',
                ),
                migrations.AddField(
                    model_name='pipelinestepoutputstodeletetemp',
                    name='pipelinestep',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.PipelineStep'),
                )]
        ),
        migrations.AlterField(
            model_name='customcablewire',
            name='dest_pin',
            field=models.IntegerField(db_column='dest_pin_id'),
        ),
        migrations.AlterField(
            model_name='customcablewire',
            name='source_pin',
            field=models.IntegerField(db_column='source_pin_id'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='transformation_ptr',
            field=models.IntegerField(db_column='transformation_ptr_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pipelineoutputcable',
            name='output_cdt',
            field=models.IntegerField(db_column='output_cdt_id', null=True),
        ),
        migrations.AlterField(
            model_name='pipelineoutputcable',
            name='source',
            field=models.IntegerField(db_column='source_id'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='transformation',
            field=models.IntegerField(db_column='transformation_id'),
        ),
        migrations.AlterField(
            model_name='pipelinestepinputcable',
            name='dest',
            field=models.IntegerField(db_column='dest_id'),
        ),
        migrations.AlterField(
            model_name='pipelinestepinputcable',
            name='source',
            field=models.IntegerField(db_column='source_id'),
        ),
    ]
