# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0103_no_default_user'),
        ('pipeline', '0100_unlink_apps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # migrations.RemoveField(
                #     model_name='pipelinestepoutputstodeletetemp',
                #     name='pipelinestep',
                # ),
                migrations.DeleteModel(
                    name='PipelineStepOutputsToDeleteTemp',
                ),
                migrations.AddField(
                    model_name='pipelinestep',
                    name='outputs_to_delete',
                    field=models.ManyToManyField(help_text='TransformationOutputs whose data should not be retained', related_name='pipeline_steps_deleting', to='transformation.TransformationOutput'),
                )]),
        migrations.AlterField(
            model_name='customcablewire',
            name='dest_pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_pins', to='metadata.CompoundDatatypeMember'),
        ),
        migrations.AlterField(
            model_name='customcablewire',
            name='source_pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_pins', to='metadata.CompoundDatatypeMember'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='transformation_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transformation.Transformation'),
        ),
        migrations.AlterField(
            model_name='pipelineoutputcable',
            name='output_cdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cables_leading_to', to='metadata.CompoundDatatype'),
        ),
        migrations.AlterField(
            model_name='pipelineoutputcable',
            name='source',
            field=models.ForeignKey(help_text='Source output hole', on_delete=django.db.models.deletion.CASCADE, to='transformation.TransformationOutput'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='transformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelinesteps', to='transformation.Transformation'),
        ),
        migrations.AlterField(
            model_name='pipelinestepinputcable',
            name='dest',
            field=models.ForeignKey(help_text='Wiring destination input hole', on_delete=django.db.models.deletion.CASCADE, related_name='cables_leading_in', to='transformation.TransformationInput'),
        ),
        migrations.AlterField(
            model_name='pipelinestepinputcable',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformation.TransformationXput'),
        ),
    ]
