# Generated by Django 2.2.18 on 2021-04-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('pipeline', '0101_squashed2'), ('pipeline', '0102_relink_apps'), ('pipeline', '0103_drop_all')]

    initial = True

    dependencies = []

    operations = []
