# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_null_state_fields_20160107_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runsic',
            old_name='runstep',
            new_name='dest_runstep',
        ),
        migrations.AlterUniqueTogether(
            name='runsic',
            unique_together=set([('dest_runstep', 'PSIC')]),
        ),
    ]
