# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_dest_runstep_20160202_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='groups_allowed',
            field=models.ManyToManyField(blank=True, help_text='What groups have access?', related_name='archive_run_has_access_to', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='run',
            name='users_allowed',
            field=models.ManyToManyField(blank=True, help_text='Which users have access?', related_name='archive_run_has_access_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
