# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0031_convert_state_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='_runstate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='archive.RunState'),
        ),
    ]
