# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0032_runstate_related_name_20160518_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runcomponent',
            name='_runcomponentstate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='runcomponents', to='archive.RunComponentState'),
        ),
    ]
