# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0033_runcomponentstate_related_name_20160527_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='_complete',
        ),
        migrations.RemoveField(
            model_name='run',
            name='_successful',
        ),
        migrations.RemoveField(
            model_name='runcomponent',
            name='_complete',
        ),
        migrations.RemoveField(
            model_name='runcomponent',
            name='_successful',
        ),
        migrations.RemoveField(
            model_name='runcomponent',
            name='is_cancelled',
        ),
    ]
