# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0034_remove_old_state_fields_20160531_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='pipeline',
            field=models.IntegerField(db_column='pipeline_id'),
        ),
        migrations.AlterField(
            model_name='runcomponent',
            name='execrecord',
            field=models.IntegerField(db_column='execrecord_id', null=True),
        ),
        migrations.AlterField(
            model_name='runinput',
            name='dataset',
            field=models.IntegerField(db_column='dataset_id'),
        ),
        migrations.AlterField(
            model_name='runoutputcable',
            name='pipelineoutputcable',
            field=models.IntegerField(db_column='pipelineoutputcable_id'),
        ),
        migrations.AlterField(
            model_name='runsic',
            name='PSIC',
            field=models.IntegerField(db_column='PSIC_id'),
        ),
        migrations.AlterField(
            model_name='runstep',
            name='pipelinestep',
            field=models.IntegerField(db_column='pipelinestep_id'),
        ),
    ]
