# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('archive', '0101_squashed'),
        ('pipeline', '0101_squashed2'),
        ('fleet', '0101_squashed'),
        # ('librarian', '0101_squashed'),
        # ('metadata', '0101_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='pipeline',
            field=models.ForeignKey(help_text='Pipeline used in this run', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_instances', to='pipeline.Pipeline'),
        ),
        migrations.AlterField(
            model_name='runcomponent',
            name='execrecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by_components', to='librarian.ExecRecord'),
        ),
        migrations.AlterField(
            model_name='runinput',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runinputs', to='librarian.Dataset'),
        ),
        migrations.AlterField(
            model_name='runoutputcable',
            name='pipelineoutputcable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poc_instances', to='pipeline.PipelineOutputCable'),
        ),
        migrations.AlterField(
            model_name='runsic',
            name='PSIC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psic_instances', to='pipeline.PipelineStepInputCable'),
        ),
        migrations.AlterField(
            model_name='runstep',
            name='pipelinestep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelinestep_instances', to='pipeline.PipelineStep'),
        ),
    ]
