# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0102_relink_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Name of this batch of runs')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Batch description')),
                ('groups_allowed', models.ManyToManyField(blank=True, help_text='What groups have access?', related_name='archive_runbatch_has_access_to', to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_allowed', models.ManyToManyField(blank=True, help_text='Which users have access?', related_name='archive_runbatch_has_access_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='run',
            name='runbatch',
            field=models.ForeignKey(blank=True, help_text='Run batch that this Run is a part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='archive.RunBatch'),
        ),
    ]
