# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0105_run_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodoutput',
            name='install_failed',
            field=models.BooleanField(default=False, help_text='Did code fail to install?'),
        ),
    ]
