# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0106_methodoutput_install_failed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runinput',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='run',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority of this Run (priority levels are defined in settings)'),
        ),
    ]
