# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0112_remove_dataset_file_source'),
        ('datachecking', '0106_baddata_file_not_stable'),
        ('archive', '0107_runinput_ordering_priority_help_text_20170403_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='runoutputcable',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='runoutputcable',
            name='pipelineoutputcable',
        ),
        migrations.RemoveField(
            model_name='runoutputcable',
            name='run',
        ),
        migrations.RemoveField(
            model_name='runoutputcable',
            name='runcomponent_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='runsic',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='runsic',
            name='PSIC',
        ),
        migrations.RemoveField(
            model_name='runsic',
            name='dest_runstep',
        ),
        migrations.RemoveField(
            model_name='runsic',
            name='runcomponent_ptr',
        ),
        migrations.DeleteModel(
            name='RunOutputCable',
        ),
        migrations.DeleteModel(
            name='RunSIC',
        ),
    ]
