# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datachecking', '0107_auto_20190614_1645'),
        ('librarian', '0113_remove_execrecord_generator'),
        ('archive', '0108_drop_cables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execlog',
            name='invoking_record',
        ),
        migrations.RemoveField(
            model_name='execlog',
            name='record',
        ),
        migrations.RemoveField(
            model_name='methodoutput',
            name='execlog',
        ),
        migrations.AlterUniqueTogether(
            name='runstep',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='runstep',
            name='pipelinestep',
        ),
        migrations.RemoveField(
            model_name='runstep',
            name='run',
        ),
        migrations.RemoveField(
            model_name='runstep',
            name='runcomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='run',
            name='parent_runstep',
        ),
        migrations.DeleteModel(
            name='ExecLog',
        ),
        migrations.DeleteModel(
            name='MethodOutput',
        ),
        migrations.DeleteModel(
            name='RunStep',
        ),
    ]
