# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0110_remove_runcomponent_execrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceedssystemcapabilities',
            name='run',
        ),
        migrations.RemoveField(
            model_name='run',
            name='_runstate',
        ),
        migrations.RemoveField(
            model_name='run',
            name='groups_allowed',
        ),
        migrations.RemoveField(
            model_name='run',
            name='paused_by',
        ),
        migrations.RemoveField(
            model_name='run',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='run',
            name='runbatch',
        ),
        migrations.RemoveField(
            model_name='run',
            name='stopped_by',
        ),
        migrations.RemoveField(
            model_name='run',
            name='user',
        ),
        migrations.RemoveField(
            model_name='run',
            name='users_allowed',
        ),
        migrations.RemoveField(
            model_name='runbatch',
            name='groups_allowed',
        ),
        migrations.RemoveField(
            model_name='runbatch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='runbatch',
            name='users_allowed',
        ),
        migrations.RemoveField(
            model_name='runcomponent',
            name='_runcomponentstate',
        ),
        migrations.RemoveField(
            model_name='runinput',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='runinput',
            name='run',
        ),
        migrations.DeleteModel(
            name='ExceedsSystemCapabilities',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
        migrations.DeleteModel(
            name='RunBatch',
        ),
        migrations.DeleteModel(
            name='RunComponent',
        ),
        migrations.DeleteModel(
            name='RunComponentState',
        ),
        migrations.DeleteModel(
            name='RunInput',
        ),
        migrations.DeleteModel(
            name='RunState',
        ),
    ]
