# Generated by Django 2.2.18 on 2021-04-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('archive', '0101_squashed'),
                ('archive', '0102_relink_apps'),
                ('archive', '0103_runbatch_20160622_1609'),
                ('archive', '0104_runbatch_on_delete_20160715_1040'),
                ('archive', '0105_run_priority'),
                ('archive', '0106_methodoutput_install_failed'),
                ('archive', '0107_runinput_ordering_priority_help_text_20170403_1547'),
                ('archive', '0108_drop_cables'),
                ('archive', '0109_drop_methodoutput_execlog_runstep'),
                ('archive', '0110_remove_runcomponent_execrecord'),
                ('archive', '0111_drop_run')]

    initial = True

    dependencies = []

    operations = []
