---

- name: create kive user
  become: true
  user:
    name: kive
    system: yes
    uid: 762  # random uid in system uid range (200, 999); hard-coded for consistency across hosts


# NOTE(nknight): this is done with `file` instead of during user creation so that we
# can set the permissions explicitly.
- name: create kive home directory
  file:
    path: /home/kive/
    state: directory
    mode: "go-rx"
    group: kive
    owner: kive


- name: create kive app directories
  become: true
  loop:
    - /etc/kive/
    - /var/log/kive/
    - /data/kive/media_root/
  file:
    path: "{{ item }}"
    state: directory
    mode: "2770"
    owner: kive
    group: kive


- name: kive environment configuration
  become: true
  become_user: kive
  block: 
    - name: set kive environment varialbes
      blockinfile:
        path: /home/kive/.bash_profile
        block: |
          # This section gets appended to the kive user's .bash_profile
          # and to /etc/sysconfig/httpd
          export KIVE_DB_NAME=kive
          export KIVE_DB_USER=kive
          export KIVE_DB_HOST=head
          export KIVE_DB_PASSWORD={{ kive_db_password }}
          
          export KIVE_MEDIA_ROOT=/var/kive/media_root
          export KIVE_STATIC_ROOT=/var/www/html/kive/static
          export KIVE_SLURM_PATH=/opt/venv_kive/bin
          
          # Other settings get appended by the bootstrap script.
        create: true  # create the file if it doesn't exist
        backup: true
        owner: kive
        group: kive
    - name: ensure kive's bashrc loads bash_profile
      lineinfile:
        path: "/home/kive/.bashrc"
        line: ". ~/.bash_profile"
        create: true  # create the file if it doesn't exist
        backup: true
        owner: kive
        group: kive


- name: fetch kive source code
  become: true
  git:
    dest: /usr/local/share/Kive
    repo: https://github.com/cfe-lab/Kive.git
    version: "{{ kive_version | default('master') }}"


- name: kive package dependencies
  become: true
  dnf:
    name:
      - platform-python-devel
      - sqlite-devel
      - words
      - lsof
      - graphviz
      - graphviz-devel


- name: install kive python dependencies
  become: true
  block:
    - name: create virtualenv
      command:
        cmd: python3 -m venv /opt/venv_kive
        creates: /opt/venv_kive
    - name: install dependencies in virtualenv
      pip:
        requirements: /usr/local/share/Kive/requirements.txt


- name: install postgres database libraries
  become: true
  block:
    - name: add postgresl package repository
      dnf:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    - name: disable built-in postgres module
      command:
        cmd: dnf -qy module disable postgresql
        warn: false  # dnf module doesn't include this sub-command, so have to use command directly
    - name: install client libraries
      dnf:
        update_cache: true
        name: postgresql12
    - name: enable postgres network traffic
      block:
        - name: ensure firewalld is running
          systemd:
            name: firewalld
            state: started
            enabled: true
        - name: add postgres exceptions to firewall
          firewalld:
            service: postgresql
            state: enabled
            permanent: true
