---

- name: kive package dependencies
  become: true
  apt:
    name:
      - python3-dev
      - python3-venv
      - libsqlite3-dev
      - wcanadian
      - lsof
      - graphviz
      - libgraphviz-dev

- name: install postgres database libraries
  become: true
  apt:
    name:
      - postgresql-client

- name: configure mail service for error logging
  block:
    - name: install postfix
      become: true
      apt:
        name:
          - postfix
    - name: start postfix daemon
      systemd:
        name: postfix
        state: started
        enabled: true

- name: create kive user
  become: true
  user:
    name: kive
    system: yes
    uid: 762  # random uid in system uid range (200, 999); hard-coded for consistency across hosts
