---

- name: install and start mariadb
  become: true
  become_user: root
  tags: slurmdb
  block:
    - name: install mariadb
      apt:
        name:
          - mariadb-server
          - libmariadb-dev
        state: present
    - name: start mariadb service
      systemd:
        name: mariadb
        state: started
        enabled: true
    - name: create slurm database user
      tags: slurmdb
      block:
        - mysql_db:
            name: slurm_acct_db
            login_unix_socket: /var/run/mysqld/mysqld.sock
            check_implicit_admin: true
            config_file: ''
            state: present
        - mysql_user:
            name: slurm
            login_unix_socket: /var/run/mysqld/mysqld.sock
            check_implicit_admin: true
            config_file: ''
            priv: "slurm_acct_db.*:all"

- name: add slurmctld config files
  become: true
  block:
    - name: copy cgroup config file
      notify: reconfigure slurm
      copy:
        src: cgroup.conf
        dest: /usr/local/etc/slurm/
        owner: slurm
        group: slurm
        mode: "644"
    - name: generate and copy slurm config file
      notify: reconfigure slurm
      template:
        src: slurm.conf.j2
        dest: /usr/local/etc/slurm/slurm.conf
        owner: slurm
        group: slurm
        mode: "644"

- name: copy slurmdbd configuration
  become: true
  copy:
    src: "slurmdbd.conf"
    dest: /usr/local/etc/slurm/
    owner: slurm
    group: slurm
    mode: "600"

- name: create directory for slurmctld spooling
  become: true
  file:
    path: /var/spool/slurmctld
    owner: slurm
    group: slurm
    mode: '0755'
    state: directory

- name: enable Slurm head-node-only services
  become: true
  block:
    - name: check if the slurmctld service is in place
      stat: path=/usr/local/lib/systemd/system/slurmctld.service
      register: slurmctld_service

    - name: fail if the slurmctld service isn't there
      fail:
        msg: "slurmctld service is not installed."
      when: not slurmctld_service.stat.exists

    - name: check if the slurmdbd service is in place
      stat: path=/usr/local/lib/systemd/system/slurmdbd.service
      register: slurmdbd_service

    - name: fail if the slurmdbd service isn't there
      fail:
        msg: "slurmdbd service is not installed."
      when: not slurmdbd_service.stat.exists

    - loop:
      - slurmdbd
      - slurmctld
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
