# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['family__name', 'tag']},
        ),
        migrations.AlterModelOptions(
            name='containerfamily',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='container',
            name='file',
            field=models.FileField(help_text='Singularity container file', upload_to=b'CodeResources', verbose_name=b'Container file'),
        ),
    ]
