# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['family__name', '-tag']},
        ),
    ]
