# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_container_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerargument',
            options={'ordering': ('app_id', 'type', 'position', 'name')},
        ),
        migrations.AlterModelOptions(
            name='containerrun',
            options={'ordering': ('-start_time',)},
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this batch of container runs', max_length=60, verbose_name='Batch Name'),
        ),
        migrations.AlterField(
            model_name='containerdataset',
            name='name',
            field=models.CharField(blank=True, help_text='Local file name, also used to sort multiple inputs for a single argument.', max_length=60),
        ),
    ]
