# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='containerrun',
            name='priority',
            field=models.IntegerField(default=0, help_text=b'Chooses which slurm queue to use.'),
        ),
        migrations.AlterField(
            model_name='containerrun',
            name='state',
            field=models.CharField(choices=[(b'N', b'New'), (b'L', b'Loading'), (b'R', b'Running'), (b'S', b'Saving'), (b'C', b'Complete'), (b'F', b'Failed'), (b'X', b'Cancelled')], default=b'N', max_length=1),
        ),
    ]
