# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0007_run_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerapp',
            options={'ordering': ('-container_id', 'name')},
        ),
        migrations.AlterModelOptions(
            name='containerdataset',
            options={'ordering': ('run', 'argument__type', 'argument__position', 'argument__name')},
        ),
        migrations.AddField(
            model_name='containerrun',
            name='slurm_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
