# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from django.db.models.expressions import F


def set_submit_time(apps, schema_editor):
    ContainerRun = apps.get_model('container', 'ContainerRun')
    ContainerRun.objects.update(submit_time=F('start_time'))


def unset_submit_time(apps, schema_editor):
    pass  # Reversal not needed.


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0008_slurm_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerrun',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text=b'When this job was put in the queue.'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='containerrun',
            options={'ordering': ('-submit_time',)},
        ),
        migrations.RunPython(set_submit_time, unset_submit_time)
    ]
