# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0010_purging_sandboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerlog',
            name='log_size',
            field=models.BigIntegerField(blank=True, help_text=b'Size of the log file in bytes.  If null, this has not been computed yet, or the log is shortand not stored in a file.', null=True),
        ),
    ]
