# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0011_containerlog_log_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerlog',
            name='long_text',
            field=models.FileField(help_text="Holds the log text if it's longer than the max length.", upload_to='ContainerLogs'),
        ),
    ]
