# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 23:43
from __future__ import unicode_literals

import container.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0012_containerlog_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Size of the container file in bytes.  If null, this has not been computed yet.', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='file',
            field=container.models.ContainerFileField(help_text='Singularity container file', upload_to='Containers', verbose_name='Container file'),
        ),
    ]
