# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-15 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0013_container_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['family__name', '-created']},
        ),
    ]
