# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0014_container_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='file_type',
            field=models.CharField(choices=[('SIMG', 'Singularity'), ('ZIP', 'Zip'), ('TAR', 'Tar'), ('TGZ', 'Gzipped tar')], default='SIMG', max_length=20),
        ),
        migrations.AddField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='container.Container'),
        ),
    ]
