# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 02:09
from __future__ import unicode_literals

import container.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0015_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='file',
            field=container.models.ContainerFileField(help_text='Singularity or archive container file', upload_to='Containers', verbose_name='Container file'),
        ),
    ]
