# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0016_container_file_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='file_type',
            field=models.CharField(choices=[('SIMG', 'Singularity'), ('ZIP', 'Zip'), ('TAR', 'Tar')], default='SIMG', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Singularity container that an archive container runs in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='container.Container'),
        ),
    ]
