# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0017_container_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerrun',
            name='sandbox_purged',
        ),
        migrations.AddField(
            model_name='containerrun',
            name='original_run',
            field=models.ForeignKey(blank=True, help_text='This run is a rerun of the original.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reruns', to='container.ContainerRun'),
        ),
    ]
