# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0019_containerrun_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerrun',
            name='is_warned',
            field=models.BooleanField(default=False, help_text='True if a warning was logged because the Slurm job failed.'),
        ),
    ]
