# Generated by Django 4.0.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0202_alter_containerrun_submit_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='containerdataset',
            constraint=models.UniqueConstraint(
                condition=models.Q(('multi_position__isnull', False)),
                fields=('run', 'argument', 'multi_position'),
                name='unique_run_arg_multi_position'),
        ),
    ]
