# Generated by Django 4.0.10

from django.db import migrations, models


def validate_existing_arguments(apps, schema_editor):
    ContainerArgument = apps.get_model('container', 'ContainerArgument')
    bad = ContainerArgument.objects.exclude(
        models.Q(type='I', position__isnull=False, allow_multiple=False)
        | models.Q(type='I', position__isnull=True)
        | models.Q(type='O', position__isnull=False)
    )
    ids = list(bad.values_list('id', flat=True))
    if ids:
        raise RuntimeError(
            f"Found {len(ids)} ContainerArgument(s) with invalid classification "
            f"(OUTPUT+null position or INPUT+non-null position+multiple): "
            f"IDs {ids}. Correct or remove these before applying the constraint."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0022_containerdataset_unique_run_arg_multi_position'),
    ]

    operations = [
        migrations.RunPython(
            validate_existing_arguments,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='containerargument',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(type='I', position__isnull=False, allow_multiple=False)
                    | models.Q(type='I', position__isnull=True)
                    | models.Q(type='O', position__isnull=False)
                ),
                name='valid_argument_classification',
            ),
        ),
    ]
