# Generated by Django 4.0.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0023_containerargument_valid_argument_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerdataset',
            name='name',
            field=models.CharField(
                blank=True,
                help_text='Local file name or directory-output relative path, '
                          'also used to sort multiple inputs for a single '
                          'argument.',
                max_length=90),
        ),
    ]
