# Generated by Django 3.2 on 2021-04-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0201_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerrun',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, help_text='When this job was put in the queue.'),
        ),
    ]
