---

- name: check if original /home has been renamed
  stat: path=/data/home
  register: data_home

- name: move /home to /data to make it accessible to workers
  become: true
  block:
  - name: create /data
    file:
      path: /data
      state: directory

  - name: move /home to /data/home
    command: mv /home /data/home

  when: not data_home.stat.exists

- name: symbolic link for /home
  become: true
  file:
    path: /home
    src: /data/home
    state: link

- name: ensure ufw is running
  become: true
  systemd:
    name: ufw
    state: started
    enabled: true

- name: open port for SSH access
  become: true
  community.general.ufw:
    rule: allow
    port: ssh
    protocol: tcp

- name: open NFS ports
  become: true
  block:
    - name: open TCP port
      community.general.ufw:
        rule: allow
        port: nfs
        proto: tcp
    - name: open UDP port
      community.general.ufw:
        rule: allow
        port: nfs
        proto: udp

- name: open port for workers to communicate with slurmctld
  become: true
  community.general.ufw:
    rule: allow
    port: 6817
    protocol: tcp

- name: install NFS server
  become: true
  apt:
    name:
      - nfs-kernel-server
    state: present

- name: start NFS service
  systemd:
    name: nfs-server
    state: started
    enabled: true

- name: set up NFS exports
  become: true
  register: nfs_exports_file
  blockinfile:
    path: /etc/exports
    block: |
      /data              192.168.56.0/255.255.255.0(rw,sync,no_all_squash,no_root_squash)
      /usr/local         192.168.56.0/255.255.255.0(ro,sync,no_root_squash)
      /opt               192.168.56.0/255.255.255.0(ro,sync,no_root_squash)

- name: reload NFS exports
  become: true
  when: nfs_exports_file.changed
  command: exportfs -r

- name: install Slurm using apt
  become: true
  apt:
    name:
      - slurm-wlm
      - slurmdbd

- name: copy slurmdbd configuration
  become: true
  copy:
    src: "slurmdbd.conf"
    dest: /etc/slurm/
    owner: slurm
    group: slurm
    mode: "644"

- name: install and start mariadb
  become: true
  become_user: root
  tags: slurmdb
  block:
    - name: install mariadb
      apt:
        name:
          - mariadb-server
          - libmariadb-dev
        state: present
    - name: start mariadb service
      systemd:
        name: mariadb
        state: started
        enabled: true
    - name: create slurm database user
      tags: slurmdb
      block:
        - mysql_db:
            name: slurm_acct_db
            # check_implicit_admin: true
            # config_file: ''
            login_host: localhost
            login_user: root
            login_password: ""
            state: present
        - mysql_user:
            name: slurm
            priv: "slurm_acct_db.*:all"

#- name: install slurm
#  become: true
#  block:
#    - name: install slurm runtime requirements
#      dnf:
#        name:
#          - hwloc
#          - libibmad
#          - libibumad
#          - lua
#          - man2html
#          - numactl
#          - openssl
#          - pam-devel
#          - perl-devel
#          - rpm-build
#          - rrdtool-devel
#    - name: install slurm from rpm files
#      dnf:
#        name:
#          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-20.02.2-1.el8.x86_64.rpm"
#          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-example-configs-20.02.2-1.el8.x86_64.rpm"
#          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-slurmctld-20.02.2-1.el8.x86_64.rpm"
#          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-slurmdbd-20.02.2-1.el8.x86_64.rpm"
#    - name: configure slurm tmpfiles
#      copy:
#        content: "d /var/run/slurm 0755 slurm slurm"
#        dest: /usr/lib/tmpfiles.d/slurm.conf
#    - block:
#        - name: fix slurmdbd pidfile path in systemd unit
#          replace:
#            path: /usr/lib/systemd/system/slurmdbd.service
#            regexp: /var/run/slurmdbd.pid
#            replace: /var/run/slurm/slurmdbd.pid
#        - name: fix slurmctld pidfile path in systemd unit
#          replace:
#            path: /usr/lib/systemd/system/slurmctld.service
#            regexp: /var/run/slurmctld.pid
#            replace: /var/run/slurm/slurmctld.pid
#    - name: enable slurm services
#      loop:
#        - slurmdbd
#        - slurmctld
#      systemd:
#        daemon_reload: true  # necessary because we've edited the unit file
#        name: "{{ item }}"
#        state: started
#        enabled: true
