---

- become: true
  block:
    - name: ensure firewalld is running
      systemd:
        name: firewalld
        state: started
        enabled: true
    - name: open slurm ports
      loop:
        - 6817-6819/tcp
        - 6817-6819/udp
        - 7321/tcp
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
    - name: mount /data
      ansible.posix.mount:
        path: /data
        src: "{{kive_db_host}}:/data"
        fstype: nfs
        state: mounted

    - name: mount /opt
      ansible.posix.mount:
        path: /opt
        src: "{{kive_db_host}}:/opt"
        fstype: nfs
        state: mounted
        opts: ro

    - name: mount /usr/local
      ansible.posix.mount:
        path: /usr/local
        src: "{{kive_db_host}}:/usr/local"
        fstype: nfs
        state: mounted
        opts: ro

    - name: check if original /home has been renamed
      stat: path=/original_home
      register: home_backed_up

    - name: rename original /home
      command: mv /home /original_home
      when: not home_backed_up.stat.exists

    - name: symbolic link for /home
      file:
        path: /home
        src: /data/home
        state: link

    - name: read system users
      register: shadow_list
      community.general.read_csv:
        path: /etc/shadow
        delimiter: ":"
        fieldnames:
          - name
          - passwd
          - lastchanged
          - min
          - max
          - warn
          - inactive
          - expire
    - name: copy system users
      loop: "{{ shadow_list.list }}"
      when: item.passwd.startswith("$")
      user:
        append: yes
        create_home: no
        name: "{{ item.name }}"
        password: "{{ item.passwd }}"
