---

- become: true
  block:
    - name: mount /data
      ansible.posix.mount:
        path: /data
        src: "{{kive_db_host}}:/data"
        fstype: nfs
        state: mounted

    - name: mount /opt
      ansible.posix.mount:
        path: /opt
        src: "{{kive_db_host}}:/opt"
        fstype: nfs
        state: mounted
        opts: ro

    - name: mount /usr/local
      ansible.posix.mount:
        path: /usr/local
        src: "{{kive_db_host}}:/usr/local"
        fstype: nfs
        state: mounted
        opts: ro

    - name: check if original /home has been renamed
      stat: path=/original_home
      register: home_backed_up

    - name: rename original /home
      command: mv /home /original_home
      when: not home_backed_up.stat.exists

    - name: symbolic link for /home
      file:
        path: /home
        src: /data/home
        state: link
