# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 18:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0007_xput_validate_slug_20150612_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformationinput',
            name='dataset_name',
            field=models.CharField(help_text='Name for input as an alternative to index', max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='input name'),
        ),
        migrations.AlterField(
            model_name='transformationoutput',
            name='dataset_name',
            field=models.CharField(help_text='Name for output as an alternative to index', max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='output name'),
        ),
    ]
