# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0101_squashed'),
        ('metadata', '0101_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xputstructure',
            name='compounddatatype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xput_structures', to='metadata.CompoundDatatype'),
        ),
    ]
