# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0102_relink_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
