# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0103_no_default_user'),
        ('portal', '0002_remove_stagedfile_20170815_1726'),
        ('method', '0111_drop_all'),
        ('pipeline', '0103_drop_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformation',
            name='groups_allowed',
        ),
        migrations.RemoveField(
            model_name='transformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transformation',
            name='users_allowed',
        ),
        migrations.AlterUniqueTogether(
            name='transformationinput',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='transformationinput',
            name='transformation',
        ),
        migrations.RemoveField(
            model_name='transformationinput',
            name='transformationxput_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='transformationoutput',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='transformationoutput',
            name='transformation',
        ),
        migrations.RemoveField(
            model_name='transformationoutput',
            name='transformationxput_ptr',
        ),
        migrations.RemoveField(
            model_name='xputstructure',
            name='compounddatatype',
        ),
        migrations.RemoveField(
            model_name='xputstructure',
            name='transf_xput',
        ),
        migrations.DeleteModel(
            name='Transformation',
        ),
        migrations.DeleteModel(
            name='TransformationInput',
        ),
        migrations.DeleteModel(
            name='TransformationOutput',
        ),
        migrations.DeleteModel(
            name='TransformationXput',
        ),
        migrations.DeleteModel(
            name='XputStructure',
        ),
    ]
