# Generated by Django 2.2.18 on 2021-04-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('transformation', '0101_squashed'),
                ('transformation', '0102_relink_apps'),
                ('transformation', '0103_no_default_user'),
                ('transformation', '0104_drop_all')]

    initial = True

    dependencies = []

    operations = []
