---

- name: create backup filesystem
  hosts: head
#  vars:
#    backup_physical_volumes:
#      - "ata-ST10000NM001G-2MW103_ZS51H7QX"
  # Replaced the above with the `backup_physical_volumes` variable in group_vars.
  tasks:
    - name: create a single partition on each of the physical volumes
      loop: "{{ backup_physical_volumes }}"
      community.general.parted:
        device: "/dev/disk/by-id/{{ item }}"
        number: 1
        state: present
        label: gpt

    - name: construct a list of the partition names
      block:
        - name: initialize the list as empty
          set_fact:
            partition_names: [ ]
        - name: append names to the list
          loop: "{{ backup_physical_volumes }}"
          set_fact:
            partition_names: "{{ partition_names + ['/dev/disk/by-id/' ~ item ~ '-part1'] }}"

    - name: create a volume group out of the partitions
      lvg:
        vg: backup-vg
        pvs: "{{ partition_names | join(',') }}"

    - name: create a logical volume from the volume group
      community.general.lvol:
        vg: backup-vg
        lv: backup-lv
        size: 100%VG

    - name: create the filesystem
      community.general.filesystem:
        fstype: ext4
        dev: /dev/backup-vg/backup-lv

    - name: create the /media/backup mount point
      file:
        path: /media/backup
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: mount the filesystem
      mount:
        path: /media/backup
        src: /dev/backup-vg/backup-lv
        fstype: ext4
        state: mounted
