---

- name: preliminary setup to run on the Octomore head node
  hosts: head
  vars:
    data_physical_volumes:
      - /dev/sdb
#  roles:
#    - create_data_filesystem
#    - head_node_internal_interface
  tasks:
    - name: create /opt
      file:
        path: /opt
        owner: root
        group: root
        mode: '0755'
        state: directory
    - name: set up head node networking
      include_role:
        name: head_node_networking
