---

- name: build Slurm on the head node
  hosts: head
  roles:
    - slurm_builder

- name: set up head node networking
  hosts: head
  roles:
    - head_node_networking

- name: configure and start slurmctld (and friends) on the head node
  hosts: head
  roles:
    - slurm_controller

- name: set up worker node networking
  hosts: workers
  roles:
    - worker_node_networking

- name: configure and start slurmd on all nodes
  hosts: all
  roles:
    - slurm_node
