---
- name: update SSL certificates
  hosts: head
  tasks:
    - name: install SSL certificate
      copy:
        src: "{{ kive_ssl_certificate_src }}"
        dest: "{{ kive_ssl_cert_path }}"
        owner: root
        group: root

    - name: install SSL key
      copy:
        src: "{{ kive_ssl_key_src }}"
        dest: "{{ kive_ssl_key_path }}"
        owner: root
        group: root
        mode: "0600"

- name: reload Apache configuration
  hosts: head
  tasks:
    - name: reload Apache configuration
      systemd:
        name: apache2
        state: reloaded
        enabled: true
        daemon_reload: true
