# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0010_coderesourcerevision_unique_together_20150604_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderesource',
            name='groups_allowed',
            field=models.ManyToManyField(blank=True, help_text='What groups have access?', related_name='method_coderesource_has_access_to', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='coderesource',
            name='users_allowed',
            field=models.ManyToManyField(blank=True, help_text='Which users have access?', related_name='method_coderesource_has_access_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coderesourcerevision',
            name='groups_allowed',
            field=models.ManyToManyField(blank=True, help_text='What groups have access?', related_name='method_coderesourcerevision_has_access_to', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='coderesourcerevision',
            name='users_allowed',
            field=models.ManyToManyField(blank=True, help_text='Which users have access?', related_name='method_coderesourcerevision_has_access_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='methodfamily',
            name='groups_allowed',
            field=models.ManyToManyField(blank=True, help_text='What groups have access?', related_name='method_methodfamily_has_access_to', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='methodfamily',
            name='users_allowed',
            field=models.ManyToManyField(blank=True, help_text='Which users have access?', related_name='method_methodfamily_has_access_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
