# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0011_permissions_remove_null_20160203_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, help_text='Where a dependency must exist in the sandbox', max_length=255, verbose_name='Dependency path')),
                ('filename', models.CharField(blank=True, help_text='The file name the dependency is given in the sandbox at execution', max_length=255, verbose_name='Dependency file name')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='method.Method')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to='method.CodeResourceRevision')),
            ],
        ),
    ]
