# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0013_transfer_crd_to_md_20160224_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coderesourcedependency',
            name='coderesourcerevision',
        ),
        migrations.RemoveField(
            model_name='coderesourcedependency',
            name='requirement',
        ),
        migrations.DeleteModel(
            name='CodeResourceDependency',
        ),
    ]
