# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0014_remove_crd_20160225_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderesource',
            name='filename',
            field=models.CharField(help_text='The filename for this resource', max_length=260, validators=[django.core.validators.RegexValidator(message='Invalid code resource filename', regex='^(\x08|([-_.()\\w]+ *)*[-_.()\\w]+)$')], verbose_name='Resource file name'),
        ),
        migrations.AlterField(
            model_name='coderesourcerevision',
            name='content_file',
            field=models.FileField(default=(), help_text='File contents of this code resource revision', upload_to='CodeResources', verbose_name='File contents'),
        ),
    ]
