# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0015_eliminate_empty_crr_add_default_20160225_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderesourcerevision',
            name='content_file',
            field=models.FileField(help_text='File contents of this code resource revision', upload_to='CodeResources', verbose_name='File contents'),
        ),
    ]
