# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 22:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0101_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderesource',
            name='filename',
            field=models.CharField(help_text='The filename for this resource', max_length=260, validators=[django.core.validators.RegexValidator(message='Filename must contain only: alphanumeric characters; spaces; and the characters -._(), and cannot start with a space', regex='^([-_.()\\w]+ *)*[-_.()\\w]+$')], verbose_name='Resource file name'),
        ),
    ]
