# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-27 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0104_dockerimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dockerimage',
            options={'ordering': ('name', 'tag')},
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='hash',
            field=models.CharField(default='dummyhash', help_text='Hash of contents', max_length=71, verbose_name='Hash'),
            preserve_default=False,
        ),
    ]
