# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0105_dockerimage_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='docker_image',
            field=models.ForeignKey(blank=True, help_text='The method will run inside this docker image.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='method.DockerImage'),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='hash',
            field=models.CharField(help_text='Hash of contents in docker', max_length=71, verbose_name='Hash'),
        ),
    ]
