# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-01 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0106_method_dockerimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dockerimage',
            options={'ordering': ('name', '-tag')},
        ),
        migrations.AlterField(
            model_name='method',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='method.CodeResourceRevision'),
        ),
    ]
