# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-29 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0107_method_driver_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimage',
            name='tag',
            field=models.CharField(help_text='Docker image tag and Git tag', max_length=128, verbose_name='Tag'),
        ),
    ]
