# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0109_method_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerimage',
            name='groups_allowed',
        ),
        migrations.RemoveField(
            model_name='dockerimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dockerimage',
            name='users_allowed',
        ),
        migrations.RemoveField(
            model_name='method',
            name='docker_image',
        ),
        migrations.DeleteModel(
            name='DockerImage',
        ),
    ]
