# Generated by Django 2.2.18 on 2021-04-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('method', '0101_squashed'),
                ('method', '0102_cr_filename_validator_message_20160624_1552'),
                ('method', '0103_method_memory'),
                ('method', '0104_dockerimage'),
                ('method', '0105_dockerimage_hash'),
                ('method', '0106_method_dockerimage'),
                ('method', '0107_method_driver_optional'),
                ('method', '0108_docker_image_tag_help'),
                ('method', '0109_method_container'),
                ('method', '0110_drop_dockerimage'),
                ('method', '0111_drop_all')]

    initial = True

    dependencies = []

    operations = []
