---

- name: check if original /home has been renamed
  stat: path=/data/home
  register: data_home

- name: move /home to /data to make it accessible to workers
  become: true
  block:
  - name: create /data
    file:
      path: /data
      owner: root
      group: root
      mode: '0755'
      state: directory
  - name: move /home to /data/home
    command: mv /home /data/home
  when: not data_home.stat.exists

- name: symbolic link for /home
  become: true
  file:
    path: /home
    src: /data/home
    state: link

- name: enable packet forwarding
  become: true
  blockinfile:
    path: /etc/ufw/sysctl.conf
    block: |
      net/ipv4/ip_forward=1

- name: configure IP masquerading
  become: true
  blockinfile:
    path: /etc/ufw/before.rules
    block: |
       *nat
       :POSTROUTING ACCEPT [0:0]
       -A POSTROUTING -s {{ internal_subnet }}/{{ internal_mask_bits }} -o {{ head_external_interface }} -j MASQUERADE
       COMMIT

- name: restart ufw to allow the new rules to take effect
  become: true
  systemd:
    name: ufw
    state: restarted
    enabled: true

- name: allow forwarded packets from the compute nodes to traverse the firewall
  become: true
  community.general.ufw:
    rule: allow
    route: true
    interface_in: "{{ head_internal_interface }}"
    interface_out: "{{ head_external_interface }}"
    from: "{{ internal_subnet }}/{{ internal_mask_bits }}"

- name: open port for SSH access
  become: true
  community.general.ufw:
    rule: allow
    port: ssh
    protocol: tcp

- name: open NFS ports
  become: true
  block:
    - name: open TCP port
      community.general.ufw:
        rule: allow
        port: nfs
        proto: tcp
    - name: open UDP port
      community.general.ufw:
        rule: allow
        port: nfs
        proto: udp

- name: open port for workers to communicate with slurmctld
  become: true
  community.general.ufw:
    rule: allow
    port: 6817
    protocol: tcp

- name: enable ufw
  become: true
  community.general.ufw:
    state: enabled

- name: install NFS server
  become: true
  apt:
    name:
      - nfs-kernel-server
    state: present

- name: start NFS service
  systemd:
    name: nfs-server
    state: started
    enabled: true

- name: set up NFS exports
  become: true
  register: nfs_exports_file
  blockinfile:
    path: /etc/exports
    block: |
      /data              {{ nfs_export_to_hosts }}(rw,sync,no_all_squash,no_root_squash)
      /usr/local         {{ nfs_export_to_hosts }}(ro,sync,no_root_squash)
      /opt               {{ nfs_export_to_hosts }}(ro,sync,no_root_squash)

- name: reload NFS exports
  become: true
  when: nfs_exports_file.changed
  command: exportfs -r

- name: install DHCP server
  become: true
  apt:
    name:
      - isc-dhcp-server

- name: configure DHCP server
  become: true
  block:
    - name: write conf file
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: "644"
        backup: true
    - name: tell dhcpd which interface to serve DHCP requests on
      template:
        src: isc-dhcp-server.j2
        dest: /etc/default/isc-dhcp-server
        owner: root
        group: root
        mode: "644"
        backup: true

- name: (re)start DHCP server
  become: true
  systemd:
    name: isc-dhcp-server
    state: restarted
    enabled: true
