# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0011_permissions_remove_null_20160203_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFileDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Human-readable name for this external file directory', max_length=4096)),
                ('path', models.CharField(help_text='Absolute path', max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='external_path',
            field=models.CharField(blank=True, help_text='Relative path of the file within the specified external file directory', max_length=4096),
        ),
        migrations.AddField(
            model_name='dataset',
            name='externalfiledirectory',
            field=models.ForeignKey(blank=True, help_text='External file directory containing the data file', null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.ExternalFileDirectory', verbose_name='External file directory'),
        ),
    ]
