# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0012_external_path_20160318_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfiledirectory',
            name='name',
            field=models.CharField(help_text='Human-readable name for this external file directory', max_length=4096, unique=True),
        ),
    ]
