# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0012_dataset_file_index_20160406_1051'),
        ('librarian', '0013_efd_name_unique_20160404_1010'),
    ]

    operations = [
    ]
