# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file_source',
            field=models.IntegerField(db_column='file_source_id', null=True),
        ),
        migrations.AlterField(
            model_name='execrecord',
            name='generator',
            field=models.IntegerField(db_column='generator_id'),
        ),
    ]
