# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0100_unlink_apps'),
        ('archive', '0001_initial'),
        ('archive', '0019_prepare_merge_dataset_SD_20151116_1012'),
        ('archive', '0020_date_created_default_20151116_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='archive.RunComponent'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='execrecord',
            name='generator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execrecord', to='archive.ExecLog'),
        ),
    ]
