# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0102_relink_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date of Dataset creation.'),
        ),
    ]
