# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0103_dataset_last_time_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='last_time_checked',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date-time of last (external) dataset existence check.', null=True),
        ),
    ]
