# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0103_index_date_created'),
        ('librarian', '0104_auto_20161014_1132'),
    ]

    operations = [
    ]
