# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0110_mark_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='is_uploaded',
            field=models.BooleanField(default=False, help_text='True if the file was uploaded, not an output.'),
        ),
    ]
