# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0110_remove_runcomponent_execrecord'),
        ('librarian', '0113_remove_execrecord_generator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetstructure',
            name='compounddatatype',
        ),
        migrations.RemoveField(
            model_name='datasetstructure',
            name='dataset',
        ),
        migrations.AlterUniqueTogether(
            name='execrecordin',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='execrecordin',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='execrecordin',
            name='execrecord',
        ),
        migrations.RemoveField(
            model_name='execrecordin',
            name='generic_input',
        ),
        migrations.AlterUniqueTogether(
            name='execrecordout',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='execrecordout',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='execrecordout',
            name='execrecord',
        ),
        migrations.RemoveField(
            model_name='execrecordout',
            name='generic_output',
        ),
        migrations.DeleteModel(
            name='DatasetStructure',
        ),
        migrations.DeleteModel(
            name='ExecRecord',
        ),
        migrations.DeleteModel(
            name='ExecRecordIn',
        ),
        migrations.DeleteModel(
            name='ExecRecordOut',
        ),
    ]
