# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datachecking', '0008_runsic_input_integrity_check_20160323_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellerror',
            name='column',
            field=models.IntegerField(db_column='column_id'),
        ),
        migrations.AlterField(
            model_name='contentchecklog',
            name='dataset',
            field=models.IntegerField(db_column='dataset_id'),
        ),
        migrations.AlterField(
            model_name='contentchecklog',
            name='execlog',
            field=models.IntegerField(db_column='execlog_id', null=True),
        ),
        migrations.AlterField(
            model_name='integritychecklog',
            name='dataset',
            field=models.IntegerField(db_column='dataset_id'),
        ),
        migrations.AlterField(
            model_name='integritychecklog',
            name='execlog',
            field=models.IntegerField(db_column='execlog_id', null=True),
        ),
        migrations.AlterField(
            model_name='integritychecklog',
            name='runsic',
            field=models.IntegerField(db_column='runsic_id', null=True),
        ),
        migrations.AlterField(
            model_name='md5conflict',
            name='conflicting_dataset',
            field=models.IntegerField(db_column='conflicting_dataset_id', null=True),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='CDTM',
            field=models.IntegerField(db_column='CDTM_id'),
        ),
    ]
