# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0101_squashed'),
        ('datachecking', '0102_relink_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='integritychecklog',
            name='runcomponent',
            field=models.OneToOneField(help_text='RunComponent responsible for copying dataset to a sandbox', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_integrity_check', to='archive.RunComponent'),
        ),
        migrations.AlterField(
            model_name='integritychecklog',
            name='execlog',
            field=models.ForeignKey(help_text='Log of the execution where dataset was produced as an output', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrity_checks', to='archive.ExecLog'),
        ),
        migrations.AlterField(
            model_name='integritychecklog',
            name='runsic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.RunSIC'),
        ),
    ]
