# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 20:43
from __future__ import unicode_literals

from django.db import migrations, transaction


@transaction.atomic
def copy_runsic_to_runcomponent(apps, schema_editor):
    """
    Update IntegrityCheckLogs to use their runcomponent field instead of their runsic field.
    """
    IntegrityCheckLog = apps.get_model("datachecking", "IntegrityCheckLog")

    for icl in IntegrityCheckLog.objects.filter(runsic__isnull=False):
        icl.runcomponent = icl.runsic
        icl.save()


@transaction.atomic
def restore_runsic(apps, schema_editor):
    """
    Reverse operation to the above.  Note that this is lossy as not all RunComponents are RunSICs.
    """
    IntegrityCheckLog = apps.get_model("datachecking", "IntegrityCheckLog")

    for icl in IntegrityCheckLog.objects.filter(runcomponent__isnull=False, runcomponent__runsic__isnull=False):
        icl.runsic = icl.runcomponent.runsic
        icl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datachecking', '0103_icl_runcomponent_20160601_1420'),
    ]

    operations = [
        migrations.RunPython(copy_runsic_to_runcomponent, restore_runsic)
    ]
