# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datachecking', '0010_icl_copy_runsic_to_runcomponent_20160601_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integritychecklog',
            name='runsic',
        ),
    ]
