# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datachecking', '0105_remove_integritychecklog_runsic'),
    ]

    operations = [
        migrations.AddField(
            model_name='baddata',
            name='file_not_stable',
            field=models.NullBooleanField(),
        ),
    ]
