# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datachecking', '0107_remove_execlog_refs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baddata',
            name='contentchecklog',
        ),
        migrations.RemoveField(
            model_name='blankcell',
            name='cellerror',
        ),
        migrations.RemoveField(
            model_name='cellerror',
            name='baddata',
        ),
        migrations.RemoveField(
            model_name='cellerror',
            name='column',
        ),
        migrations.RemoveField(
            model_name='cellerror',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentchecklog',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='contentchecklog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='integritychecklog',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='integritychecklog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='md5conflict',
            name='conflicting_dataset',
        ),
        migrations.RemoveField(
            model_name='md5conflict',
            name='integritychecklog',
        ),
        migrations.RemoveField(
            model_name='verificationlog',
            name='CDTM',
        ),
        migrations.RemoveField(
            model_name='verificationlog',
            name='contentchecklog',
        ),
        migrations.DeleteModel(
            name='BadData',
        ),
        migrations.DeleteModel(
            name='BlankCell',
        ),
        migrations.DeleteModel(
            name='CellError',
        ),
        migrations.DeleteModel(
            name='ContentCheckLog',
        ),
        migrations.DeleteModel(
            name='IntegrityCheckLog',
        ),
        migrations.DeleteModel(
            name='MD5Conflict',
        ),
        migrations.DeleteModel(
            name='VerificationLog',
        ),
    ]
