# Generated by Django 2.2.18 on 2021-04-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('datachecking', '0101_squashed'),
                ('datachecking', '0102_relink_apps'),
                ('datachecking', '0103_icl_runcomponent_20160601_1420'),
                ('datachecking', '0104_icl_copy_runsic_to_runcomponent_20160601_1343'),
                ('datachecking', '0105_remove_integritychecklog_runsic'),
                ('datachecking', '0106_baddata_file_not_stable'),
                ('datachecking', '0107_remove_execlog_refs'),
                ('datachecking', '0108_drop_all')]

    initial = True

    dependencies = []

    operations = []
