---

- name: create slurm user
  become: true
  user:
    name: slurm
    system: true
    uid: 9634

- name: create slurm data directories
  become: true
  loop:
    - /var/log/slurm
    - /var/run/slurm
    - /var/lib/slurm
    - /etc/slurm
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    group: slurm

- name: add slurm config files
  become: true
  block:
    - name: copy cgroup config file
      copy:
        src: cgroup.conf
        dest: /etc/slurm/
        owner: slurm
        group: slurm
        mode: "644"
    - name: generate and copy slurm config file
      template:
        src: slurm.conf.j2
        dest: /etc/slurm/slurm.conf
        owner: slurm
        group: slurm
        mode: "644"


- name: enable slurm network access
  become: true
  block:
    - name: ensure firewalld is running
      systemd:
        name: firewalld
        state: started
        enabled: true
    - name: open slurm ports
      loop:
        - 6817-6819/tcp
        - 6817-6819/udp
        - 7321/tcp
      firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true

- name: network drive mounts
  become: true
  block:
  - loop: "{{ network_mounts }}"
    name: "{{ item.name }}"
    ansible.posix.mount:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      fstype: "{{ item.fstype }}"
      state: "{{ item.state }}"
      opts: "{{ item.opts }}"
