---

- name: install epel-release
  become: true
  dnf:
    name: epel-release
    state: present


- name: install and start mariadb
  become: true
  become_user: root
  tags: slurmdb
  block:
    - name: install mariadb
      dnf:
        name:
          - mariadb-server
          - mariadb-devel
        state: present
    - name: start mariadb service
      systemd:
        name: mariadb
        state: started
        enabled: true


- name: prepare slurm configuration
  become: true
  block:
    - name: create slurm user
      user:
        name: slurm
        system: true
    - name: create slurm data directories
      loop:
        - /var/log/slurm
        - /var/run/slurm
        - /var/lib/slurm
        - /etc/slurm
      file:
        path: "{{ item }}"
        state: directory
        owner: slurm
        group: slurm
    - name: add slurm config files
      loop:
        - ../../common-files/slurm.conf
        - ../../common-files/cgroup.conf
        - slurmdbd.conf
      copy:
        src: "{{ item }}"
        dest: /etc/slurm/
        owner: slurm
        group: slurm
        mode: "644"
    - name: create slurm database user
      tags: slurmdb
      become: true
      block:
        - mysql_db:
            name: slurm_acct_db
        - mysql_user:
            name: slurm
            priv: "slurm_acct_db.*:all"


- name: install slurm
  become: true
  block:
    - name: install slurm runtime requirements
      dnf:
        name:
          - hwloc
          - libibmad
          - libibumad
          - lua
          - man2html
          - numactl
          - openssl
          - pam-devel
          - perl-devel
          - rpm-build
          - rrdtool-devel
    - name: install slurm from rpm files
      dnf:
        name:
          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-20.02.2-1.el8.x86_64.rpm"
          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-example-configs-20.02.2-1.el8.x86_64.rpm"
          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-slurmctld-20.02.2-1.el8.x86_64.rpm"
          - "{{ slurmbuilddir }}/rpmbuild/RPMS/x86_64/slurm-slurmdbd-20.02.2-1.el8.x86_64.rpm"
    - name: configure slurm tmpfiles
      copy:
        content: "d /var/run/slurm 0755 slurm slurm"
        dest: /usr/lib/tmpfiles.d/slurm.conf
    - block:
        - name: fix slurmdbd pidfile path in systemd unit
          replace:
            path: /usr/lib/systemd/system/slurmdbd.service
            regexp: /var/run/slurmdbd.pid
            replace: /var/run/slurm/slurmdbd.pid
        - name: fix slurmctld pidfile path in systemd unit
          replace:
            path: /usr/lib/systemd/system/slurmctld.service
            regexp: /var/run/slurmctld.pid
            replace: /var/run/slurm/slurmctld.pid
    - name: enable slurm services
      loop:
        - slurmdbd
        - slurmctld
      systemd:
        daemon_reload: true  # necessary because we've edited the unit file
        name: "{{ item }}"
        state: started
        enabled: true

